name: Light Chocolate
referenceUrls: 
  - https://www.youtube.com/watch?v=YyNNWmWGtI4&t=496s
productType: CREAMi Original
ingredients:
  - 440 g, 2% milk
  - 2 g, vanilla extract
  - 50 g, Swerve
  - 8 g, cocoa powder
  - 1 g, salt
  - 1 g, xanthan gum
steps:
  - Mix all dry ingredients in bowl.
  - Add wet ingredients into high sided mixing container.
  - Using an immersion blender, slowly pour in dry ingredients into the wet container.
  - Pour into pint, up to the max fill line, and freeze for 24 hours.
  - Take the pint out of freezer, let sit out on the counter for 5 mins.
  - Run sides under hot water for 30 secs.
  - Install pint, choose LIGHT ICE CREAM and spin. Required one re-spin.
notes:
  - date: 08/06/24
    text: Using Ice-21 w/ deluxe recipe. Processed for about 15 mins. very fluffy. Added a handful of marsallows as well. After storing in freezer overnight, required time to thaw before consumption. Ebded up being ok, however was not as good as with creami. Updated scores to reflect.
  - date: 03/14/24
    text: Try decreasing Swerve in next batch. This was a winner.
  - date: 05/26/25
    text: Used ICE-21, however used Deluxe ingredient sizing (660g of milk). Good decision since after churning was at rim. Served two, made popsicles with remainder.